----------------------------------
-- Data Visualization in Tableu --
----------------------------------

/*
Author:			Arturo Contreras Montoya
Dataset:		https://ourworldindata.org/covid-deaths
Description:	qs_ used to export data to Tableu Public
*/


-- =================================================


USE COVID_PROJECT
GO

-- 1. DEATH PERCENTAGE
SELECT SUM(NEW_CASES)                                   AS TOTAL_CASES
  , SUM(CAST(NEW_DEATHS AS INT))                        AS TOTAL_DEATHS
  , SUM(CAST(NEW_DEATHS AS INT)) / SUM(NEW_CASES) * 100 AS DEATH_PERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1, 2
GO


-- 2. TOTAL DEATHS BY CONTINENT
SELECT LOCATION
  , SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATH_COUNT
FROM COVID_DEATHS
WHERE CONTINENT IS NULL
    AND LOCATION IN ('Europe', 'Asia', 'North America', 'South America', 'Africa', 'Oceania')
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC
GO


-- 3. TOTAL INFECTIONS AND PERCET BY COUNTRY
SELECT LOCATION
  , POPULATION
  , MAX(TOTAL_CASES)                      AS HIGHEST_INFECTION_COUNT
  , MAX((TOTAL_CASES / POPULATION)) * 100 AS POPULATION_INFECTION_PERCET
FROM COVID_DEATHS
GROUP BY LOCATION
  , POPULATION
ORDER BY POPULATION_INFECTION_PERCET DESC
GO


-- 4. TOTAL INFECTIONS AND PERCET BY COUNTRY PER DATE
-- Same as [3.] but deatiled by date.
SELECT LOCATION
  , POPULATION
  , DATE
  , MAX(TOTAL_CASES)                      AS HIGHEST_INFECTION_COUNT
  , MAX((TOTAL_CASES / POPULATION)) * 100 AS POPULATION_INFECTION_PERCET
FROM COVID_DEATHS
GROUP BY LOCATION
  , POPULATION
  , DATE
ORDER BY POPULATION_INFECTION_PERCET DESC